CREATE TABLE votes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    theme_id BIGINT UNSIGNED NOT NULL,
    choice_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_vote_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_vote_theme FOREIGN KEY (theme_id) REFERENCES themes(id) ON DELETE CASCADE,
    CONSTRAINT fk_vote_choice FOREIGN KEY (choice_id) REFERENCES choices(id) ON DELETE CASCADE,
    CONSTRAINT unique_vote UNIQUE (user_id, theme_id, choice_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
